version: "3.8"

services:
  app:
    image: wefox:local
    container_name: wefox
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    links:
        - db
        - redis
    volumes:
      - .:/app

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    env_file:
      - .env

  redis:
    container_name: wefox-redis
    image: redis:latest
    restart: on-failure
    ports:
      - "6379:6379"
volumes:
  db_data: